user-message: ! ' Ensure the following libraries are installed on your system.

* brew install devil

* brew install pngquant

'

flags: {}

packages:
  - '.'
  - location:
      git: https://github.com/RaphaelJ/friday-devil.git
      commit: 73181586307a4db93302bfeb9af9ded615e60a07
    extra-dep: true

extra-deps:
  - friday-0.2.3.1
  - friday-devil-0.1.1.1
  - ratio-int-0.1.2

extra-include-dirs:
  - /usr/local/Cellar/devil/1.7.8_3/include

extra-lib-dirs:
  - /usr/local/Cellar/devil/1.7.8_3/lib

resolver: lts-9.0
