user-message: ! ' Ensure the following libraries are installed on your system.

* brew install devil

* brew install pngquant

'

flags: {}

packages:
  - .

extra-deps:
  - friday-0.2.3.1
  - ratio-int-0.1.2

extra-include-dirs:
  - /usr/local/Cellar/devil/1.8.0_1/include

extra-lib-dirs:
  - /usr/local/Cellar/devil/1.8.0_1/lib

resolver: lts-9.6
